### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by RAHUL-DOGNEY** [mahbubsabuj/restaurant-management-system#3]
how to run front end .
Please give a command

**Comment by mahbubsabuj** [comment]
Use this command to install nx.dev globally npm install -g nx
Then open frontend folder in vs code. Install nx console extension from vs code store. You can use nx console to run the app. Or you can use ng serve admin-panel or npx nx serve admin-panel to run the app.

**Comment by RAHUL-DOGNEY** [comment]
Thanks you Bhiyaa

**Comment by mahbubsabuj** [comment]
Welcome vai.
